export const vehiclesData = [
    { callsign: 'BD-309', name: 'Ambulance', registeredCity: 'Badin' },
    { callsign: 'BD-310', name: 'Ambulance', registeredCity: 'Badin' },
    { callsign: 'BD-311', name: 'Ambulance', registeredCity: 'Badin' },
    { callsign: 'BD-312', name: 'Ambulance', registeredCity: 'Badin' },
    { callsign: 'BD-313', name: 'Ambulance', registeredCity: 'Badin' },
    { callsign: 'M-05', name: 'Mobile Unit', registeredCity: 'Badin' },
    { callsign: 'BT-271', name: 'Ambulance', registeredCity: 'Bathoro' },
    { callsign: 'BT-272', name: 'Ambulance', registeredCity: 'Bathoro' },
    { callsign: 'BT-273', name: 'Ambulance', registeredCity: 'Bathoro' },
    { callsign: 'BT-274', name: 'Ambulance', registeredCity: 'Bathoro' },
    { callsign: 'BT-275', name: 'Ambulance', registeredCity: 'Bathoro' },
    { callsign: 'DA-439', name: 'Ambulance', registeredCity: 'Dadu' },
    { callsign: 'DA-440', name: 'Ambulance', registeredCity: 'Dadu' },
    { callsign: 'DA-391', name: 'Ambulance', registeredCity: 'Dadu' },
    { callsign: 'GH-337', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'GH-338', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'GH-339', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'GH-340', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'GH-341', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'GH-342', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'GH-343', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'GH-344', name: 'Ambulance', registeredCity: 'Ghotki' },
    { callsign: 'KP-404', name: 'Ambulance', registeredCity: 'Hingroja' },
    { callsign: 'KP-405', name: 'Ambulance', registeredCity: 'Hingroja' },
    { callsign: 'KP-406', name: 'Ambulance', registeredCity: 'Hingroja' },
    { callsign: 'KP-407', name: 'Ambulance', registeredCity: 'Hingroja' },
    { callsign: 'KP-408', name: 'Ambulance', registeredCity: 'Hingroja' },
    { callsign: 'HY-292', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-293', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-294', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-295', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-296', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-297', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-298', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-299', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-300', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-301', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-302', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-303', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'HY-317', name: 'Ambulance', registeredCity: 'Hyderabad' },
    { callsign: 'M-21', name: 'Mobile Unit', registeredCity: 'Hyderabad' },
    { callsign: 'JB-277', name: 'Ambulance', registeredCity: 'Jacobabad' },
    { callsign: 'JB-374', name: 'Ambulance', registeredCity: 'Jacobabad' },
    { callsign: 'JB-375', name: 'Ambulance', registeredCity: 'Jacobabad' },
    { callsign: 'JB-376', name: 'Ambulance', registeredCity: 'Jacobabad' },
    { callsign: 'JB-377', name: 'Ambulance', registeredCity: 'Jacobabad' },
    { callsign: 'JB-378', name: 'Ambulance', registeredCity: 'Jacobabad' },
    { callsign: 'M-04', name: 'Mobile Unit', registeredCity: 'Jacobabad' },
    { callsign: 'KA-370', name: 'Ambulance', registeredCity: 'Kandhkot' },
    { callsign: 'KA-371', name: 'Ambulance', registeredCity: 'Kandhkot' },
    { callsign: 'KA-372', name: 'Ambulance', registeredCity: 'Kandhkot' },
    { callsign: 'KA-373', name: 'Ambulance', registeredCity: 'Kandhkot' },
    { callsign: 'KA-500', name: 'Ambulance', registeredCity: 'Kandhkot' },
    { callsign: 'M-10', name: 'Mobile Unit', registeredCity: 'Kandhkot' },
    { callsign: 'KA-369', name: 'Ambulance', registeredCity: 'Kashmore' },
    { callsign: 'KA-501', name: 'Ambulance', registeredCity: 'Kashmore' },
    { callsign: 'KA-502', name: 'Ambulance', registeredCity: 'Kashmore' },
    { callsign: 'KA-506', name: 'Ambulance', registeredCity: 'Kashmore' },
    { callsign: 'KP-400', name: 'Ambulance', registeredCity: 'Khairpur' },
    { callsign: 'KP-401', name: 'Ambulance', registeredCity: 'Khairpur' },
    { callsign: 'KP-402', name: 'Ambulance', registeredCity: 'Khairpur' },
    { callsign: 'KP-403', name: 'Ambulance', registeredCity: 'Khairpur' },
    { callsign: 'KP-437', name: 'Ambulance', registeredCity: 'Khairpur' },
    { callsign: 'KP-438', name: 'Ambulance', registeredCity: 'Khairpur' },
    { callsign: 'M-09', name: 'Mobile Unit', registeredCity: 'Khairpur' },
    { callsign: 'LA-278', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-279', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-280', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-281', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-282', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-283', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-284', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-285', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-286', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-287', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-288', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-289', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'LA-290', name: 'Ambulance', registeredCity: 'Larkano' },
    { callsign: 'M-22', name: 'Mobile Unit', registeredCity: 'Larkano' },
    { callsign: 'MA-412', name: 'Ambulance', registeredCity: 'Matiari' },
    { callsign: 'MA-413', name: 'Ambulance', registeredCity: 'Matiari' },
    { callsign: 'MA-414', name: 'Ambulance', registeredCity: 'Matiari' },
    { callsign: 'MA-415', name: 'Ambulance', registeredCity: 'Matiari' },
    { callsign: 'MA-416', name: 'Ambulance', registeredCity: 'Matiari' },
    { callsign: 'M-20', name: 'Mobile Unit', registeredCity: 'Matiari' },
    { callsign: 'MK-347', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-349', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-350', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-351', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-352', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-353', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-354', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-355', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-356', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'MK-357', name: 'Ambulance', registeredCity: 'Mirpurkhas' },
    { callsign: 'M-19', name: 'Mobile Unit', registeredCity: 'Mirpurkhas' },
    { callsign: 'TP-427', name: 'Ambulance', registeredCity: 'Mithi' },
    { callsign: 'TP-428', name: 'Ambulance', registeredCity: 'Mithi' },
    { callsign: 'TP-430', name: 'Ambulance', registeredCity: 'Mithi' },
    { callsign: 'NF-395', name: 'Ambulance', registeredCity: 'Naushero Feroze' },
    { callsign: 'NF-396', name: 'Ambulance', registeredCity: 'Naushero Feroze' },
    { callsign: 'NF-409', name: 'Ambulance', registeredCity: 'Naushero Feroze' },
    { callsign: 'NF-410', name: 'Ambulance', registeredCity: 'Naushero Feroze' },
    { callsign: 'NF-411', name: 'Ambulance', registeredCity: 'Naushero Feroze' },
    { callsign: 'TP-497', name: 'Ambulance', registeredCity: 'Nagarparkar' },
    { callsign: 'TP-498', name: 'Ambulance', registeredCity: 'Nagarparkar' },
    { callsign: 'TP-499', name: 'Ambulance', registeredCity: 'Nagarparkar' },
    { callsign: 'HY-318', name: 'Ambulance', registeredCity: 'Shaheed Benazirabad' },
    { callsign: 'SB-384', name: 'Ambulance', registeredCity: 'Shaheed Benazirabad' },
    { callsign: 'SB-385', name: 'Ambulance', registeredCity: 'Shaheed Benazirabad' },
    { callsign: 'SB-386', name: 'Ambulance', registeredCity: 'Shaheed Benazirabad' },
    { callsign: 'SB-387', name: 'Ambulance', registeredCity: 'Shaheed Benazirabad' },
    { callsign: 'SB-388', name: 'Ambulance', registeredCity: 'Shaheed Benazirabad' },
    { callsign: 'M-03', name: 'Mobile Unit', registeredCity: 'Shaheed Benazirabad' },
    { callsign: 'LA-291', name: 'Ambulance', registeredCity: 'Qambar' },
    { callsign: 'QS-304', name: 'Ambulance', registeredCity: 'Qambar' },
    { callsign: 'QS-305', name: 'Ambulance', registeredCity: 'Qambar' },
    { callsign: 'SB-379', name: 'Ambulance', registeredCity: 'Qazi Ahmed' },
    { callsign: 'SB-380', name: 'Ambulance', registeredCity: 'Qazi Ahmed' },
    { callsign: 'SB-381', name: 'Ambulance', registeredCity: 'Qazi Ahmed' },
    { callsign: 'SB-382', name: 'Ambulance', registeredCity: 'Qazi Ahmed' },
    { callsign: 'SB-383', name: 'Ambulance', registeredCity: 'Qazi Ahmed' },
    { callsign: 'ME-420', name: 'Ambulance', registeredCity: 'Mehar/Radhan' },
    { callsign: 'ME-421', name: 'Ambulance', registeredCity: 'Mehar/Radhan' },
    { callsign: 'TH-253', name: 'Ambulance', registeredCity: 'Sakro' },
    { callsign: 'TH-258', name: 'Ambulance', registeredCity: 'Sakro' },
    { callsign: 'TH-259', name: 'Ambulance', registeredCity: 'Sakro' },
    { callsign: 'TH-261', name: 'Ambulance', registeredCity: 'Sakro' },
    { callsign: 'TH-262', name: 'Ambulance', registeredCity: 'Sakro' },
    { callsign: 'SG-422', name: 'Ambulance', registeredCity: 'Sanghar' },
    { callsign: 'SG-423', name: 'Ambulance', registeredCity: 'Sanghar' },
    { callsign: 'SG-424', name: 'Ambulance', registeredCity: 'Sanghar' },
    { callsign: 'SG-319', name: 'Ambulance', registeredCity: 'Sanghar' },
    { callsign: 'JA-359', name: 'Ambulance', registeredCity: 'Sehwan' },
    { callsign: 'JA-360', name: 'Ambulance', registeredCity: 'Sehwan' },
    { callsign: 'JA-361', name: 'Ambulance', registeredCity: 'Sehwan' },
    { callsign: 'JA-362', name: 'Ambulance', registeredCity: 'Sehwan' },
    { callsign: 'JA-363', name: 'Ambulance', registeredCity: 'Sehwan' },
    { callsign: 'QS-306', name: 'Ambulance', registeredCity: 'Shahdadkot' },
    { callsign: 'QS-307', name: 'Ambulance', registeredCity: 'Shahdadkot' },
    { callsign: 'QS-308', name: 'Ambulance', registeredCity: 'Shahdadkot' },
    { callsign: 'M-02', name: 'Mobile Unit', registeredCity: 'Shahdadkot' },
    { callsign: 'SH-364', name: 'Ambulance', registeredCity: 'Shikarpur' },
    { callsign: 'SH-365', name: 'Ambulance', registeredCity: 'Shikarpur' },
    { callsign: 'SH-366', name: 'Ambulance', registeredCity: 'Shikarpur' },
    { callsign: 'SH-367', name: 'Ambulance', registeredCity: 'Shikarpur' },
    { callsign: 'SH-368', name: 'Ambulance', registeredCity: 'Shikarpur' },
    { callsign: 'SH-390', name: 'Ambulance', registeredCity: 'Shikarpur' },
    { callsign: 'SH-392', name: 'Ambulance', registeredCity: 'Shikarpur' },
    { callsign: 'M-24', name: 'Mobile Unit', registeredCity: 'Shikarpur' },
    { callsign: 'SU-265', name: 'Ambulance', registeredCity: 'Sujawal' },
    { callsign: 'SU-266', name: 'Ambulance', registeredCity: 'Sujawal' },
    { callsign: 'SU-268', name: 'Ambulance', registeredCity: 'Sujawal' },
    { callsign: 'SU-269', name: 'Ambulance', registeredCity: 'Sujawal' },
    { callsign: 'SU-270', name: 'Ambulance', registeredCity: 'Sujawal' },
    { callsign: 'M-08', name: 'Mobile Unit', registeredCity: 'Sujawal' },
    { callsign: 'SK-320', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-321', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-322', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-323', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-324', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-325', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-326', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-327', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-328', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-329', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'SK-330', name: 'Ambulance', registeredCity: 'Sukkur' },
    { callsign: 'M-15', name: 'Mobile Unit', registeredCity: 'Sukkur' },
    { callsign: 'M-07', name: 'Mobile Unit', registeredCity: 'Tando Allahyar' },
    { callsign: 'TA-393', name: 'Ambulance', registeredCity: 'Tando Allahyar' },
    { callsign: 'TA-394', name: 'Ambulance', registeredCity: 'Tando Allahyar' },
    { callsign: 'TA-397', name: 'Ambulance', registeredCity: 'Tando Allahyar' },
    { callsign: 'TA-398', name: 'Ambulance', registeredCity: 'Tando Allahyar' },
    { callsign: 'TH-252', name: 'Ambulance', registeredCity: 'Thatta' },
    { callsign: 'TH-254', name: 'Ambulance', registeredCity: 'Thatta' },
    { callsign: 'TH-255', name: 'Ambulance', registeredCity: 'Thatta' },
    { callsign: 'TH-256', name: 'Ambulance', registeredCity: 'Thatta' },
    { callsign: 'TH-257', name: 'Ambulance', registeredCity: 'Thatta' },
    { callsign: 'M-25', name: 'Mobile Unit', registeredCity: 'Thatta' },
    { callsign: 'TM-260', name: 'Ambulance', registeredCity: 'Tando Muhammad Khan' },
    { callsign: 'TM-263', name: 'Ambulance', registeredCity: 'Tando Muhammad Khan' },
    { callsign: 'TM-264', name: 'Ambulance', registeredCity: 'Tando Muhammad Khan' },
    { callsign: 'TM-276', name: 'Ambulance', registeredCity: 'Tando Muhammad Khan' },
    { callsign: 'TM-389', name: 'Ambulance', registeredCity: 'Tando Muhammad Khan' },
    { callsign: 'M-17', name: 'Mobile Unit', registeredCity: 'Tando Muhammad Khan' },
    { callsign: 'UK-345', name: 'Ambulance', registeredCity: 'Umerkot' },
    { callsign: 'UK-346', name: 'Ambulance', registeredCity: 'Umerkot' },
    { callsign: 'UK-348', name: 'Ambulance', registeredCity: 'Umerkot' },
    { callsign: 'UK-358', name: 'Ambulance', registeredCity: 'Umerkot' },
    { callsign: 'UK-399', name: 'Ambulance', registeredCity: 'Umerkot' },
    { callsign: 'UK-494', name: 'Ambulance', registeredCity: 'Umerkot' },
    { callsign: 'UK-495', name: 'Ambulance', registeredCity: 'Umerkot' },
    { callsign: 'UK-496', name: 'Ambulance', registeredCity: 'Umerkot' },
];